server:
  port: 7888
spring:
  application:
    name: producer
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092         #Kafka?????????
          zk-nodes: localhost:2181        #Zookeeper????????????,???
          auto-create-topics: true        #?????false,???????Topic ????Topic???????????
      bindings:
        output_add:
          destination: bill_add
          content-type: text/plain
        output_del:
          destination: bill_del
          content-type: text/plain
        output_update:
          destination: bill_update
          content-type: text/plain    #????????????????????????
