server:
  port: 7888
spring:
  application:
    name: producer
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092         #Kafka?????????
          zk-nodes: localhost:2181        #Zookeeper????????????,???
          auto-create-topics: true        #?????false,???????Topic ????Topic???????????
      bindings:
        output:      #???stream????????output?????????output
          destination: stream-demo    #????????
          content-type: text/plain    #????????????????????????
